// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET
  balance = balance + $1,
  updated_at = NOW()
WHERE id = $2
RETURNING id, customer_id, account_number, currency, balance, status, created_at, updated_at
`

type AddAccountBalanceParams struct {
	Amount decimal.Decimal `json:"amount"`
	ID     int64           `json:"id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (customer_id, account_number, currency)
VALUES ($1, $2, $3)
RETURNING id, customer_id, account_number, currency, balance, status, created_at, updated_at
`

type CreateAccountParams struct {
	CustomerID    int64  `json:"customer_id"`
	AccountNumber string `json:"account_number"`
	Currency      string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.CustomerID, arg.AccountNumber, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, customer_id, account_number, currency, balance, status, created_at, updated_at FROM accounts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, customer_id, account_number, currency, balance, status, created_at, updated_at FROM accounts
WHERE id = $1
LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByCustomer = `-- name: ListAccountsByCustomer :many
SELECT id, customer_id, account_number, currency, balance, status, created_at, updated_at FROM accounts
WHERE customer_id = $1
ORDER BY id
`

func (q *Queries) ListAccountsByCustomer(ctx context.Context, customerID int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.AccountNumber,
			&i.Currency,
			&i.Balance,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts
SET
  status = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, account_number, currency, balance, status, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
