// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: audit_logs.sql

package sqlc

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (table_name, record_id, operation, old_values, new_values, changed_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, table_name, record_id, operation, old_values, new_values, changed_by, changed_at
`

type CreateAuditLogParams struct {
	TableName string  `json:"table_name"`
	RecordID  int64   `json:"record_id"`
	Operation string  `json:"operation"`
	OldValues []byte  `json:"old_values"`
	NewValues []byte  `json:"new_values"`
	ChangedBy *string `json:"changed_by"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TableName,
		arg.RecordID,
		arg.Operation,
		arg.OldValues,
		arg.NewValues,
		arg.ChangedBy,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TableName,
		&i.RecordID,
		&i.Operation,
		&i.OldValues,
		&i.NewValues,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const listAuditLogsByRecord = `-- name: ListAuditLogsByRecord :many
SELECT id, table_name, record_id, operation, old_values, new_values, changed_by, changed_at FROM audit_logs
WHERE table_name = $1 AND record_id = $2
ORDER BY changed_at DESC
`

type ListAuditLogsByRecordParams struct {
	TableName string `json:"table_name"`
	RecordID  int64  `json:"record_id"`
}

func (q *Queries) ListAuditLogsByRecord(ctx context.Context, arg ListAuditLogsByRecordParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByRecord, arg.TableName, arg.RecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Operation,
			&i.OldValues,
			&i.NewValues,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
