// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID            int64           `json:"id"`
	CustomerID    int64           `json:"customer_id"`
	AccountNumber string          `json:"account_number"`
	Currency      string          `json:"currency"`
	Balance       decimal.Decimal `json:"balance"`
	Status        string          `json:"status"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Admin struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AuditLog struct {
	ID        int64     `json:"id"`
	TableName string    `json:"table_name"`
	RecordID  int64     `json:"record_id"`
	Operation string    `json:"operation"`
	OldValues []byte    `json:"old_values"`
	NewValues []byte    `json:"new_values"`
	ChangedBy *string   `json:"changed_by"`
	ChangedAt time.Time `json:"changed_at"`
}

type Customer struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Transaction struct {
	ID            int64           `json:"id"`
	AccountID     int64           `json:"account_id"`
	Type          string          `json:"type"`
	Amount        decimal.Decimal `json:"amount"`
	BalanceBefore decimal.Decimal `json:"balance_before"`
	BalanceAfter  decimal.Decimal `json:"balance_after"`
	Reference     *string         `json:"reference"`
	Description   *string         `json:"description"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Transfer struct {
	ID            int64              `json:"id"`
	FromAccountID int64              `json:"from_account_id"`
	ToAccountID   int64              `json:"to_account_id"`
	Amount        decimal.Decimal    `json:"amount"`
	Fee           decimal.Decimal    `json:"fee"`
	Status        string             `json:"status"`
	Reference     *string            `json:"reference"`
	Description   *string            `json:"description"`
	CreatedAt     time.Time          `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}
