// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteCustomer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetCustomer(ctx context.Context, id int64) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccountsByCustomer(ctx context.Context, customerID int64) ([]Account, error)
	ListAuditLogsByRecord(ctx context.Context, arg ListAuditLogsByRecordParams) ([]AuditLog, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error)
}

var _ Querier = (*Queries)(nil)
